"""utc timestamps for pool_slots and replenish_jobs

Revision ID: 37f602c5a96a
Revises: 0011
Create Date: 2026-07-27 15:00:00.851205
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '37f602c5a96a'
down_revision: Union[str, None] = '0011'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_deleted_items_item_id'), table_name='deleted_items')
    op.drop_table('deleted_items')
    op.drop_index(op.f('ix_vessel_jobs_status'), table_name='vessel_jobs')
    op.drop_table('vessel_jobs')
    op.drop_index(op.f('ix_users_azure_oid'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('uq_approval_requests_pending_dest_filename'), table_name='approval_requests', postgresql_where="((status)::text = 'pending'::text)")
    op.drop_index(op.f('ix_session_audit_created_at'), table_name='session_audit_log')
    op.drop_index(op.f('ix_session_audit_email'), table_name='session_audit_log')
    op.drop_index(op.f('ix_session_audit_event'), table_name='session_audit_log')
    op.create_index(op.f('ix_session_audit_log_created_at'), 'session_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_session_audit_log_email'), 'session_audit_log', ['email'], unique=False)
    op.create_index(op.f('ix_session_audit_log_event'), 'session_audit_log', ['event'], unique=False)
    op.create_index(op.f('ix_session_audit_log_session_id'), 'session_audit_log', ['session_id'], unique=False)
    op.drop_index(op.f('ix_upload_jobs_drive_item_id'), table_name='upload_jobs')
    op.drop_constraint(op.f('upload_jobs_folder_id_fkey'), 'upload_jobs', type_='foreignkey')
    op.drop_column('upload_jobs', 'drive_item_id')
    op.drop_column('upload_jobs', 'folder_id')
    op.drop_constraint(op.f('user_profiles_email_key'), 'user_profiles', type_='unique')
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=True)
    op.drop_index(op.f('ix_user_sessions_email_status'), table_name='user_sessions')
    op.drop_index(op.f('uq_user_sessions_session_id'), table_name='user_sessions')
    op.create_index(op.f('ix_user_sessions_email'), 'user_sessions', ['email'], unique=False)
    op.create_index(op.f('ix_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_foreign_key(None, 'user_sessions', 'user_profiles', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_user_sessions_session_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_email'), table_name='user_sessions')
    op.create_index(op.f('uq_user_sessions_session_id'), 'user_sessions', ['session_id'], unique=True)
    op.create_index(op.f('ix_user_sessions_email_status'), 'user_sessions', ['email', 'status'], unique=False)
    op.drop_index(op.f('ix_user_profiles_email'), table_name='user_profiles')
    op.create_index(op.f('ix_user_profiles_email'), 'user_profiles', ['email'], unique=False)
    op.create_unique_constraint(op.f('user_profiles_email_key'), 'user_profiles', ['email'], postgresql_nulls_not_distinct=False)
    op.add_column('upload_jobs', sa.Column('folder_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('upload_jobs', sa.Column('drive_item_id', sa.VARCHAR(length=512), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('upload_jobs_folder_id_fkey'), 'upload_jobs', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_upload_jobs_drive_item_id'), 'upload_jobs', ['drive_item_id'], unique=False)
    op.drop_index(op.f('ix_session_audit_log_session_id'), table_name='session_audit_log')
    op.drop_index(op.f('ix_session_audit_log_event'), table_name='session_audit_log')
    op.drop_index(op.f('ix_session_audit_log_email'), table_name='session_audit_log')
    op.drop_index(op.f('ix_session_audit_log_created_at'), table_name='session_audit_log')
    op.create_index(op.f('ix_session_audit_event'), 'session_audit_log', ['event'], unique=False)
    op.create_index(op.f('ix_session_audit_email'), 'session_audit_log', ['email'], unique=False)
    op.create_index(op.f('ix_session_audit_created_at'), 'session_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('uq_approval_requests_pending_dest_filename'), 'approval_requests', ['destination_folder_id', 'filename'], unique=True, postgresql_where="((status)::text = 'pending'::text)")
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('azure_oid', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('tenant_id', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('display_name', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('given_name', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(length=160), autoincrement=False, nullable=True),
    sa.Column('preferred_username', sa.VARCHAR(length=320), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('users_pkey'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_azure_oid'), 'users', ['azure_oid'], unique=True)
    op.create_table('vessel_jobs',
    sa.Column('id', sa.VARCHAR(length=32), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('result_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('error', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('vessel_jobs_pkey'))
    )
    op.create_index(op.f('ix_vessel_jobs_status'), 'vessel_jobs', ['status'], unique=False)
    op.create_table('deleted_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.VARCHAR(length=256), autoincrement=False, nullable=False),
    sa.Column('item_type', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('deleted_items_pkey'))
    )
    op.create_index(op.f('ix_deleted_items_item_id'), 'deleted_items', ['item_id'], unique=True)
    # ### end Alembic commands ###
